### ISSUE TITLE
Usage in Bucklescript

### ISSUE THREAD

**Issue by idkjs** [Risto-Stevcev/lambda-streams#1]
Greetings sir. Thanks for sharing this library.

I tried using this in a bucklescript project but could not seem to get anything to run.

I tried repurposing the test examples but could not get them to go after removing the native only ocaml tests.

Would you happen to have some bucklescript examples laying around that you might share?

Thank you.

**Comment by Risto-Stevcev** [comment]
Hey, thanks for showing interest in this library!
https://github.com/Risto-Stevcev/lambda-streams/blob/master/lambda_streams_js/test/Example.ml

It's easy to work with in JS but needs some more work on the native OCaml side since functions are blocking by default.
There's a more interesting version of this library in pure Bucklescript that's unpublished (started but not finished), that I might eventually find time to integrate. It includes behaviors similar to Conal Elliott's [push-pull FRP](http://conal.net/papers/push-pull-frp/push-pull-frp.pdf).

**Comment by idkjs** [comment]
Awesome. Can't wait to see it. Stick on a unpublished branch so I can check it out!

I'm wondering if I can use this to back a binding to [phoenix-js](https://github.com/phoenixframework/phoenix)

**Comment by idkjs** [comment]
Hey boss. Ran you example. Works. Thanks. Seems with no namespace in `bsconfig.json` you have to mess around with the config to get access to the functions like so: https://github.com/idkjs/rescript-deno-template/blob/lamba-streams/bsconfig.json. Just an FYI.

**Comment by Risto-Stevcev** [comment]
It should work on `bs-platform@9.0.0`, this is how I set it up:
`bsconfig.json`
```json
{
  "name": "try-lambda-streams-js",
  "version": "0.1.0",
  "scripts": {
    "clean": "bsb -clean-world",
    "build": "bsb -make-world",
    "watch": "bsb -make-world -w"
  },
  "keywords": [
    "BuckleScript"
  ],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "bs-platform": "^9.0.0"
  },
  "dependencies": {
    "lambda-streams": "^0.1.2"
  }
}
```
`src/demo.ml`
```ocaml
open LambdaStreams

let () =
  Finite.Sync.from_list [1; 1; 2; 3; 5; 8]
  |> Finite.Sync.map (( * ) 2)
  |> Finite.Sync.pipe (Finite.Sync.make_output Js.log)
```

Admittedly though I haven't kept up with all of the bucklescript (now rescript) changes

**Comment by idkjs** [comment]
Works.
